[package]
name = "crossroads"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.6", package = "gtk4" }
gio = "0.14"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
regex = "1.11.1"
